var files =
[
    [ "AbsoluteIMU.h", null, null ],
    [ "ACCLNx.h", null, null ],
    [ "AngleSensor.h", null, null ],
    [ "BaseI2CDevice.h", null, null ],
    [ "DISTNx.h", null, null ],
    [ "LightSensorArray.h", null, null ],
    [ "LineLeader.h", null, null ],
    [ "MagicWand.h", null, null ],
    [ "MsTimer2.h", null, null ],
    [ "NumericPad.h", null, null ],
    [ "NXShield.h", "_n_x_shield_8h.html", "_n_x_shield_8h" ],
    [ "NXShieldAGS.h", null, null ],
    [ "NXShieldI2C.h", null, null ],
    [ "NXTCam.h", null, null ],
    [ "NXTCurrentMeter.h", null, null ],
    [ "NXTHID.h", null, null ],
    [ "NXTLight.h", null, null ],
    [ "NXTMMX.h", null, null ],
    [ "NXTPowerMeter.h", null, null ],
    [ "NXTServo.h", null, null ],
    [ "NXTTouch.h", null, null ],
    [ "NXTUS.h", null, null ],
    [ "NXTVoltMeter.h", null, null ],
    [ "PFMate.h", null, null ],
    [ "PSPNx.h", null, null ],
    [ "RCXLight.h", null, null ],
    [ "RTC.h", null, null ],
    [ "SHDefines.h", "_s_h_defines_8h.html", "_s_h_defines_8h" ],
    [ "SoftI2cMaster.h", null, null ],
    [ "SumoEyes.h", null, null ]
];