/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/jgrizou/workspace/code/lego/catkin_ws/src/roslego/srv/battery_voltage.srv
 *
 */


#ifndef ROSLEGO_MESSAGE_BATTERY_VOLTAGE_H
#define ROSLEGO_MESSAGE_BATTERY_VOLTAGE_H

#include <ros/service_traits.h>


#include <roslego/battery_voltageRequest.h>
#include <roslego/battery_voltageResponse.h>


namespace roslego
{

struct battery_voltage
{

typedef battery_voltageRequest Request;
typedef battery_voltageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct battery_voltage
} // namespace roslego


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roslego::battery_voltage > {
  static const char* value()
  {
    return "78b08b1408586613a7b39667400173e2";
  }

  static const char* value(const ::roslego::battery_voltage&) { return value(); }
};

template<>
struct DataType< ::roslego::battery_voltage > {
  static const char* value()
  {
    return "roslego/battery_voltage";
  }

  static const char* value(const ::roslego::battery_voltage&) { return value(); }
};


// service_traits::MD5Sum< ::roslego::battery_voltageRequest> should match 
// service_traits::MD5Sum< ::roslego::battery_voltage > 
template<>
struct MD5Sum< ::roslego::battery_voltageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roslego::battery_voltage >::value();
  }
  static const char* value(const ::roslego::battery_voltageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roslego::battery_voltageRequest> should match 
// service_traits::DataType< ::roslego::battery_voltage > 
template<>
struct DataType< ::roslego::battery_voltageRequest>
{
  static const char* value()
  {
    return DataType< ::roslego::battery_voltage >::value();
  }
  static const char* value(const ::roslego::battery_voltageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roslego::battery_voltageResponse> should match 
// service_traits::MD5Sum< ::roslego::battery_voltage > 
template<>
struct MD5Sum< ::roslego::battery_voltageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roslego::battery_voltage >::value();
  }
  static const char* value(const ::roslego::battery_voltageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roslego::battery_voltageResponse> should match 
// service_traits::DataType< ::roslego::battery_voltage > 
template<>
struct DataType< ::roslego::battery_voltageResponse>
{
  static const char* value()
  {
    return DataType< ::roslego::battery_voltage >::value();
  }
  static const char* value(const ::roslego::battery_voltageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSLEGO_MESSAGE_BATTERY_VOLTAGE_H
