"""autogenerated by genpy from roslego/motor_action.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motor_action(genpy.Message):
  _md5sum = "a9cd8a8245ed8f77485f23b78d324966"
  _type = "roslego/motor_action"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 motor_id
uint8 option
uint32 value
uint8 speed
bool direction


"""
  __slots__ = ['motor_id','option','value','speed','direction']
  _slot_types = ['uint8','uint8','uint32','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor_id,option,value,speed,direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motor_action, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motor_id is None:
        self.motor_id = 0
      if self.option is None:
        self.option = 0
      if self.value is None:
        self.value = 0
      if self.speed is None:
        self.speed = 0
      if self.direction is None:
        self.direction = False
    else:
      self.motor_id = 0
      self.option = 0
      self.value = 0
      self.speed = 0
      self.direction = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2BI2B.pack(_x.motor_id, _x.option, _x.value, _x.speed, _x.direction))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.motor_id, _x.option, _x.value, _x.speed, _x.direction,) = _struct_2BI2B.unpack(str[start:end])
      self.direction = bool(self.direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2BI2B.pack(_x.motor_id, _x.option, _x.value, _x.speed, _x.direction))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.motor_id, _x.option, _x.value, _x.speed, _x.direction,) = _struct_2BI2B.unpack(str[start:end])
      self.direction = bool(self.direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2BI2B = struct.Struct("<2BI2B")
